model:
  name: "BarlowTwins"
  backbone:
    name: "Resnet50"
    pretrained: false
  projection_dim: 8192
  hidden_dim: 8192

train:
  tag: "barlow_twins_1shot"
  batch_size: 4
  num_workers: 2
  total_epoch: 12
  lr: 0.01

  # dataset
  dataset: "DebugDataset"

  # loss
  loss:
    name: BarlowTwinsLoss
    lambda: 0.005

  # log and save
  num_iter_log: 10
  num_epoch_save_model: 2
  base_save_dir: "./work_dirs"
