model:
  name: "MoCoV3"
  backbone:
    name: "Resnet50"
    pretrained: false
  projection_dim: 256
  hidden_dim: 2048
  momentum: 0.999

train:
  tag: "moco_v3_1shot"
  batch_size: 4
  num_workers: 2
  total_epoch: 12
  lr: 0.01

  # dataset
  dataset: "DebugDataset"

  # loss
  loss:
    name: MoCoV3NCELoss
    temperature: 0.07

  # log and save
  num_iter_log: 10
  num_epoch_save_model: 2
  base_save_dir: "./work_dirs"
