model:
  name: "SimSiam"
  backbone:
    name: "Resnet50"
    pretrained: false
  projection_dim: 128
  proj_hidden_dim: 1024
  pred_hidden_dim: 1024

train:
  tag: "simsiam_1shot"
  batch_size: 4
  num_workers: 2
  total_epoch: 12
  lr: 0.01

  # dataset
  dataset: "DebugDataset"

  # loss
  loss:
    name: NegCosLoss

  # log and save
  num_iter_log: 10
  num_epoch_save_model: 2
  base_save_dir: "./work_dirs"
